### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by JamesParkDev** [hulun-studios/QuickEditor#1]
- [ ] Better redo/undo

- [ ] add .gitignore

- [ ] More types like YML, env...

- [ ] Metadata system JSON<key, value|Object>

- [ ] Formater create JSON with simple clicks

**Comment by JamesParkDev** [comment]
And line system !
